## DataFrame Introduction

1. DataFrame()
2. Hetrogenuous
3. Ordered
4. Mutable,size Mutable
5. Duplicate allowed
6. 2D data structure of pandas
7. Row and columns

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame()
type(df)

pandas.DataFrame

In [4]:
df =pd.DataFrame([[101,"Pratham",40000],[102,"harshal",50000],[103,"vansh",55000]],columns =['ID','NAME','SAL'])
df # using list

    ID     NAME    SAL
0  101  Pratham  40000
1  102  harshal  50000
2  103    vansh  55000

In [5]:
df['ID']

0    101
1    102
2    103
Name: ID, dtype: int64

In [6]:
df['NAME']

0    Pratham
1    harshal
2      vansh
Name: NAME, dtype: str

In [7]:
df2 =pd.DataFrame({'ID':[101,102,103],
                   'NAME':['pratham','harshal','vansh'],
                   'SAL':[30000,40000,50000]})
df2 # using Dictonary

    ID     NAME    SAL
0  101  pratham  30000
1  102  harshal  40000
2  103    vansh  50000

In [8]:
df3=df.set_index('ID')

In [9]:

df3.loc[101:102]

        NAME    SAL
ID
101  Pratham  40000
102  harshal  50000

In [10]:
df3.iloc[0:2]

        NAME    SAL
ID
101  Pratham  40000
102  harshal  50000

In [11]:
iris= pd.read_csv("C:/Users/ASUS/Downloads/Iris (1).csv")
iris

     Sepal_Length  Sepal_Width  Petal_Length  Petal_Width    Species
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [12]:
iris.head() # starting 5 rows

   Sepal_Length  Sepal_Width  Petal_Length  Petal_Width Species
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [13]:
iris.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Sepal_Length  150 non-null    float64
 1   Sepal_Width   150 non-null    float64
 2   Petal_Length  150 non-null    float64
 3   Petal_Width   150 non-null    float64
 4   Species       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

In [14]:
iris.describe()

       Sepal_Length  Sepal_Width  Petal_Length  Petal_Width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [15]:
iris.loc[0]

Sepal_Length       5.1
Sepal_Width        3.5
Petal_Length       1.4
Petal_Width        0.2
Species         Setosa
Name: 0, dtype: object

In [16]:
iris['Sepal_Length'].mean()

np.float64(5.843333333333334)

In [17]:
iris['Sepal_Length'].agg(['mean','max','min','sum'])

mean      5.843333
max       7.900000
min       4.300000
sum     876.500000
Name: Sepal_Length, dtype: float64

In [18]:
iris['Species'].unique()

<StringArray>
['Setosa', 'Versicolor', 'Virginica']
Length: 3, dtype: str

In [19]:
iris['Species'].value_counts()

Species
Setosa        50
Versicolor    50
Virginica     50
Name: count, dtype: int64

In [ ]:
# inplace means original me delete kartahai

In [21]:

iris.drop('Species',axis=1,inplace=True)