In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("C:/Users/ASUS/Downloads/student_10.csv")
df

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
3  06-07-2021         NaN     11        0.0         NaN
4  07-07-2021      1005.0     11        4.0         NaN
5  08-07-2021         NaN     11       10.0         NaN
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        10 non-null     str
 1   Student ID  7 non-null      float64
 2   Class       10 non-null     int64
 3   Study hrs   8 non-null      float64
 4   Percentage  7 non-null      float64
dtypes: float64(3), int64(1), str(1)
memory usage: 532.0 bytes

In [4]:
df['Class'] == 12

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8     True
9     True
Name: Class, dtype: bool

In [5]:
df[df['Class'] == 12]

         Date  Student ID  Class  Study hrs  Percentage
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [6]:
df[df["Percentage"] > 50]

         Date  Student ID  Class  Study hrs  Percentage
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [7]:
df["Student ID"]==1008.0

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7     True
8    False
9    False
Name: Student ID, dtype: bool

In [8]:
df[df["Student ID"]==1008.0]

         Date  Student ID  Class  Study hrs  Percentage
7  10-07-2021      1008.0     12        NaN        90.0

In [9]:
df[df["Student ID"]==1008.0]["Percentage"]

7    90.0
Name: Percentage, dtype: float64

In [10]:
df.loc[df["Student ID"]==1008.0]["Percentage"] = 95
df

C:\Users\ASUS\AppData\Local\Temp\ipykernel_5248\3050637766.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df.loc[df["Student ID"]==1008.0]["Percentage"] = 95

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
3  06-07-2021         NaN     11        0.0         NaN
4  07-07-2021      1005.0     11        4.0         NaN
5  08-07-2021         NaN     11       10.0         NaN
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [13]:
df1 =pd.DataFrame({'id':[101,102,103],'Name':["pratham","harshal","vansh"]})
df1

    id     Name
0  101  pratham
1  102  harshal
2  103    vansh

In [12]:
df2 =pd.DataFrame({'dept_id':[1,2,1],"dname":["Admin","IT","Admin"]})
df2

   dept_id  dname
0        1  Admin
1        2     IT
2        1  Admin

In [14]:
pd.concat([df1,df2],axis=1)

    id     Name  dept_id  dname
0  101  pratham        1  Admin
1  102  harshal        2     IT
2  103    vansh        1  Admin

In [15]:
pd.concat([df1,df2])

      id     Name  dept_id  dname
0  101.0  pratham      NaN    NaN
1  102.0  harshal      NaN    NaN
2  103.0    vansh      NaN    NaN
0    NaN      NaN      1.0  Admin
1    NaN      NaN      2.0     IT
2    NaN      NaN      1.0  Admin

In [16]:
emp=pd.DataFrame({"id":[101,102,103,104],"Name":["pratham","harshal","vansh","jay"],"did":[1,2,3,4]})
emp

    id     Name  did
0  101  pratham    1
1  102  harshal    2
2  103    vansh    3
3  104      jay    4

In [17]:
dept = pd.DataFrame({"did":[1,2,3,4],"dName":["Admin","IT","Sales","Bussiness"]})
dept

   did      dName
0    1      Admin
1    2         IT
2    3      Sales
3    4  Bussiness

In [18]:
pd.merge(emp,dept,how="inner")

    id     Name  did      dName
0  101  pratham    1      Admin
1  102  harshal    2         IT
2  103    vansh    3      Sales
3  104      jay    4  Bussiness

In [19]:
pd.merge(emp,dept,how="left")

    id     Name  did      dName
0  101  pratham    1      Admin
1  102  harshal    2         IT
2  103    vansh    3      Sales
3  104      jay    4  Bussiness

In [20]:
pd.merge(emp,dept,how="right")

    id     Name  did      dName
0  101  pratham    1      Admin
1  102  harshal    2         IT
2  103    vansh    3      Sales
3  104      jay    4  Bussiness

In [21]:
pd.merge(emp,dept,how='outer',left_on ='did',right_on='did')

    id     Name  did      dName
0  101  pratham    1      Admin
1  102  harshal    2         IT
2  103    vansh    3      Sales
3  104      jay    4  Bussiness