In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("C:/Users/ASUS/Downloads/student_10.csv")
df

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
3  06-07-2021         NaN     11        0.0         NaN
4  07-07-2021      1005.0     11        4.0         NaN
5  08-07-2021         NaN     11       10.0         NaN
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [3]:
df.head()

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
3  06-07-2021         NaN     11        0.0         NaN
4  07-07-2021      1005.0     11        4.0         NaN

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        10 non-null     str
 1   Student ID  7 non-null      float64
 2   Class       10 non-null     int64
 3   Study hrs   8 non-null      float64
 4   Percentage  7 non-null      float64
dtypes: float64(3), int64(1), str(1)
memory usage: 532.0 bytes

In [5]:
df.isnull() # give null data in boolean format

    Date  Student ID  Class  Study hrs  Percentage
0  False       False  False      False       False
1  False       False  False      False       False
2  False        True  False      False       False
3  False        True  False      False        True
4  False       False  False      False        True
5  False        True  False      False        True
6  False       False  False      False       False
7  False       False  False       True       False
8  False       False  False       True       False
9  False       False  False      False       False

In [6]:
df.isnull().sum() # give count of null data

Date          0
Student ID    3
Class         0
Study hrs     2
Percentage    3
dtype: int64

In [7]:
df.dropna() # remove all null data

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
6  09-07-2021      1007.0     12        4.0        80.0
9  12-07-2021      1010.0     12        6.0        85.0

In [8]:
med_per =df["Percentage"].median()
med_per

np.float64(80.0)

In [9]:
df["Percentage"] = df["Percentage"].fillna(med_per)

In [10]:
mean_sh =df["Study hrs"].mean()
mean_sh

np.float64(4.375)

In [11]:
df["Study hrs"] = df["Study hrs"].fillna(mean_sh)
df

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10      2.000        50.0
1  02-07-2021      1002.0     10      6.000        80.0
2  03-07-2021         NaN     10      3.000        60.0
3  06-07-2021         NaN     11      0.000        80.0
4  07-07-2021      1005.0     11      4.000        80.0
5  08-07-2021         NaN     11     10.000        80.0
6  09-07-2021      1007.0     12      4.000        80.0
7  10-07-2021      1008.0     12      4.375        90.0
8  11-07-2021      1009.0     12      4.375        60.0
9  12-07-2021      1010.0     12      6.000        85.0

In [12]:
df["Student ID"].interpolate() # automatic equally distributed

0    1001.0
1    1002.0
2    1003.0
3    1004.0
4    1005.0
5    1006.0
6    1007.0
7    1008.0
8    1009.0
9    1010.0
Name: Student ID, dtype: float64

In [13]:
df["Student ID"].bfill() # behind fill

0    1001.0
1    1002.0
2    1005.0
3    1005.0
4    1005.0
5    1007.0
6    1007.0
7    1008.0
8    1009.0
9    1010.0
Name: Student ID, dtype: float64

In [14]:
df["Student ID"].ffill() # forward fill

0    1001.0
1    1002.0
2    1002.0
3    1002.0
4    1005.0
5    1005.0
6    1007.0
7    1008.0
8    1009.0
9    1010.0
Name: Student ID, dtype: float64

In [15]:
df["Student ID"] =df["Student ID"].interpolate()
df

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10      2.000        50.0
1  02-07-2021      1002.0     10      6.000        80.0
2  03-07-2021      1003.0     10      3.000        60.0
3  06-07-2021      1004.0     11      0.000        80.0
4  07-07-2021      1005.0     11      4.000        80.0
5  08-07-2021      1006.0     11     10.000        80.0
6  09-07-2021      1007.0     12      4.000        80.0
7  10-07-2021      1008.0     12      4.375        90.0
8  11-07-2021      1009.0     12      4.375        60.0
9  12-07-2021      1010.0     12      6.000        85.0

In [16]:
df.isnull().sum()

Date          0
Student ID    0
Class         0
Study hrs     0
Percentage    0
dtype: int64

In [17]:
res =df.groupby("Class")
res

In [18]:
list(res)

[(10,
           Date  Student ID  Class  Study hrs  Percentage
  0  01-07-2021      1001.0     10        2.0        50.0
  1  02-07-2021      1002.0     10        6.0        80.0
  2  03-07-2021      1003.0     10        3.0        60.0),
 (11,
           Date  Student ID  Class  Study hrs  Percentage
  3  06-07-2021      1004.0     11        0.0        80.0
  4  07-07-2021      1005.0     11        4.0        80.0
  5  08-07-2021      1006.0     11       10.0        80.0),
 (12,
           Date  Student ID  Class  Study hrs  Percentage
  6  09-07-2021      1007.0     12      4.000        80.0
  7  10-07-2021      1008.0     12      4.375        90.0
  8  11-07-2021      1009.0     12      4.375        60.0
  9  12-07-2021      1010.0     12      6.000        85.0)]

In [19]:
data =dict(list(res))
data

{10:          Date  Student ID  Class  Study hrs  Percentage
 0  01-07-2021      1001.0     10        2.0        50.0
 1  02-07-2021      1002.0     10        6.0        80.0
 2  03-07-2021      1003.0     10        3.0        60.0,
 11:          Date  Student ID  Class  Study hrs  Percentage
 3  06-07-2021      1004.0     11        0.0        80.0
 4  07-07-2021      1005.0     11        4.0        80.0
 5  08-07-2021      1006.0     11       10.0        80.0,
 12:          Date  Student ID  Class  Study hrs  Percentage
 6  09-07-2021      1007.0     12      4.000        80.0
 7  10-07-2021      1008.0     12      4.375        90.0
 8  11-07-2021      1009.0     12      4.375        60.0
 9  12-07-2021      1010.0     12      6.000        85.0}

In [20]:
data[10]

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021      1003.0     10        3.0        60.0

In [21]:
rec_10 = data[10]

In [22]:

rec_10["Percentage"].mean()

np.float64(63.333333333333336)

In [23]:
rec_10["Study hrs"].sum()

np.float64(11.0)